name: Azure Static Web Apps CI/CD (Alternative)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install dependencies
        working-directory: frontend
        run: npm ci --prefer-offline --no-audit

      - name: Build application
        working-directory: frontend
        run: npm run build
        env:
          NEXT_PUBLIC_API_URL: https://advanced-ai-agent-0003.azurewebsites.net
          NEXT_PUBLIC_APP_NAME: Advanced AI Agent
          NEXT_PUBLIC_APP_VERSION: 1.0.0
          NEXT_PUBLIC_ENVIRONMENT: production

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/out/
          retention-days: 1

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@latest
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/frontend"
          output_location: "out"
          skip_app_build: true
          skip_api_build: true