name: Deploy New Frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend-new/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy New Frontend to Azure
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'frontend-new/package-lock.json'

      - name: Install dependencies
        run: |
          cd frontend-new
          npm ci

      - name: Build Tailwind CSS
        run: |
          cd frontend-new
          npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@latest
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/frontend-new"
          api_location: ""
          output_location: ""
          skip_app_build: true
          skip_api_build: true